// samples/astro-sample/src/components/svelte/BlogExperience.svelte
<script lang="ts">
  import type { ContentProps } from '@optimizely/cms-sdk';
  import { getPreviewUtils } from '@optimizely/cms-sdk/core';
  import type { BlogExperienceContentType } from '@/lib/contentTypes';
  import OptimizelyComponent from './optimizely/OptimizelyComponent.svelte';
  import OptimizelyComposition from './optimizely/OptimizelyComposition.svelte';

  let { content }: { content: ContentProps<typeof BlogExperienceContentType> } = $props();

  const { pa } = $derived(getPreviewUtils(content));
</script>

<main class="blog-experience">
  <header class="blog-header">
    <h1 {...pa('title')}>{content.title}</h1>
    <p {...pa('subtitle')}>{content.subtitle}</p>
  </header>
  <section class="blog-articles" {...pa('articles')}>
    {#each content.articles ?? [] as article}
      <OptimizelyComponent content={article} />
    {/each}
  </section>
  <OptimizelyComposition nodes={content.composition.nodes ?? []} />
</main>

// samples/astro-sample/src/components/react/BlogExperience.tsx
import type { ContentProps } from '@optimizely/cms-sdk';
import {
  type ComponentContainerProps,
  getPreviewUtils,
  OptimizelyComponent,
  OptimizelyComposition,
} from '@optimizely/cms-sdk/react/server';
import { BlogExperienceContentType } from '@/lib/contentTypes';

type Props = {
  content: ContentProps<typeof BlogExperienceContentType>;
};

function ComponentWrapper({ children, node }: ComponentContainerProps) {
  const { pa } = getPreviewUtils(node);
  return <div {...pa(node)}>{children}</div>;
}

export default function BlogExperience({ content }: Props) {
  const { pa } = getPreviewUtils(content);
  return (
    <main className='blog-experience'>
      <header className='blog-header'>
        <h1 {...pa('title')}>{content.title}</h1>
        <p {...pa('subtitle')}>{content.subtitle}</p>
      </header>
      <section className='blog-articles' {...pa('articles')}>
        {content?.articles?.map((article, index) => (
          <OptimizelyComponent key={index} content={article} />
        ))}
      </section>
      <OptimizelyComposition nodes={content.composition.nodes ?? []} ComponentWrapper={ComponentWrapper} />
    </main>
  );
}
