// samples/astro-sample/src/components/svelte/SmallFeature.svelte
<script lang="ts">
  import { damAssets, type ContentProps } from '@optimizely/cms-sdk';
  import { getPreviewUtils } from '@optimizely/cms-sdk/core';
  import type { SmallFeatureContentType } from '@/lib/contentTypes';
  import RichText from './optimizely/RichText.svelte';

  let { content }: { content: ContentProps<typeof SmallFeatureContentType> } = $props();

  const { pa, src } = $derived(getPreviewUtils(content));
  const { getAlt } = $derived(damAssets(content));
  const imageUrl = $derived(src(content.image));
</script>

<div class="small-feature-grid">
  <h3 {...pa('heading')}>{content.heading}</h3>
  <div style="position: relative">
    {#if imageUrl}
      <img src={imageUrl} alt={getAlt(content.image, 'image')} {...pa('image')} />
    {/if}
  </div>
  <RichText content={content.body?.json} />
</div>

// samples/astro-sample/src/components/react/SmallFeature.tsx
import { damAssets, type ContentProps } from '@optimizely/cms-sdk';
import { RichText } from '@optimizely/cms-sdk/react/richText';
import { getPreviewUtils } from '@optimizely/cms-sdk/react/server';
import { SmallFeatureContentType } from '@/lib/contentTypes';

type Props = {
  content: ContentProps<typeof SmallFeatureContentType>;
};

export default function SmallFeature({ content }: Props) {
  const { pa, src } = getPreviewUtils(content);
  const { getAlt } = damAssets(content);
  const imageUrl = src(content.image);

  return (
    <div className='small-feature-grid'>
      <h3 {...pa('heading')}>{content.heading}</h3>
      <div style={{ position: 'relative' }}>
        {imageUrl ?
          // eslint-disable-next-line @next/next/no-img-element
          <img src={imageUrl} alt={getAlt(content.image, 'image')} {...pa('image')} />
        : null}
      </div>
      <RichText content={content.body?.json} />
    </div>
  );
}
